algoritmo "temperatura"
// Função : conversao de celisus em fahrenheit de 10 em 10
// Autor :  Matheus Azevedo
// Data : 28/08/2021
// Seção de Declarações 
var
   celsius, fahrenheit : real
inicio
// Seção de Comandos 
   celsius <- 0
   enquanto celsius <= 100 faca
            escreval("Em celsius: ", celsius)
            fahrenheit <- 1.8 * celsius + 32
            escreval("Em fahrenheit: ", fahrenheit)
            celsius <- celsius + 10
   fimenquanto
fimalgoritmo
